project file added and commited from branch
eyoab01/mobile-portfolio-project-final pull request #1
Opened 2022-08-27 10:10 UTC by eyoab01

in the project index.html,style.css and readme files are added and updated.

2022-08-27 18:03 UTC, KDlamini commented
## Status: Invalid 🔴 

### Hi @eyoab01  🙋‍♀️,  

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project, that does not have a Pull Request description. Kindly write a summary of the features that you implemented in this milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-27 19:12 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @eyoab01👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 19:12 UTC, thecodechaser commented on index.html
> +        </div>
- [ ] Please reduce the left-right margin from the project card and make sure it matches [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) the design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/187044668-ac8733dd-84fb-4738-a884-41145a73ed22.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/187044676-0b35081f-f6aa-4c95-8ea7-95d228bb844b.png)
****

2022-08-27 19:12 UTC, thecodechaser commented on style.css
> +}
- [ ] Good job using the `FlexBox` for project cards. Please use the `CSS grid` for the project's main container as requested in the project requirements.
![image](https://user-images.githubusercontent.com/83803414/187044801-324bd5fb-3e83-4bb5-873e-eaabd0d7e483.png)

2022-08-27 22:39 UTC, eyoab01 commented
portfolio project all sections added.

2022-08-27 23:03 UTC, eyoab01 commented
Got it, thanks!

On Sat, Aug 27, 2022 at 10:13 PM Ranjeet Singh ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: CHANGES REQUIRED ♻️ Hi @eyoab01 <https://github.com/eyoab01>👋,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> To Highlight 🎉
>
>    - No linter errors. ✔️
>    - GitHub flow is followed. ✔️
>    - Professional README file. ✔️
>    - PR has a good title and summary. ✔️
>
>
> <https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
> N/A
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#discussion_r956613911>
> :
>
> > +      <div class="card">
>
> +        <div class="card-img">
>
> +          <img src="./images/Snapshoot-Portfolio-4.png" alt="Tonic" />
>
> +        </div>
>
> +
>
> +        <div class="details">
>
> +          <h2>Multi-Post Stories</h2>
>
> +          <ul>
>
> +            <li>CANOPY</li>
>
> +            <li>Back End Dev</li>
>
> +            <li>2015</li>
>
> +          </ul>
>
> +          <p>
>
> +            A daily selection of privately personalized reads; no accounts or
>
> +            sign-ups required.
>
> +          </p>
>
> +          <menu>
>
> +            <li>HTML</li>
>
> +            <li>CSS</li>
>
> +            <li>JavaScript</li>
>
> +          </menu>
>
> +          <a class="btn-action">See Project</a>
>
> +        </div>
>
>
>
>    - Please reduce the left-right margin from the project card and make
>    sure it matches Figma
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1>
>    the design.
>
> Your design
>
> [image: image]
> <https://user-images.githubusercontent.com/83803414/187044668-ac8733dd-84fb-4738-a884-41145a73ed22.png>
> Figma design
>
> [image: image]
> <https://user-images.githubusercontent.com/83803414/187044676-0b35081f-f6aa-4c95-8ea7-95d228bb844b.png>
> ------------------------------
> ------------------------------
>
> In style.css
> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#discussion_r956614232>
> :
>
> > +#projects {
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  align-items: center;
>
> +  padding: 142px 142px;
>
> +}
>
> +
>
> +.card {
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  max-width: 330px;
>
> +  background: #fff;
>
> +  border: 2px solid #dfe1e6;
>
> +  border-radius: 16px;
>
> +  box-shadow: 0 0 0.5px 0.25px inset #c8c6c6;
>
> +  padding: 16px 16px 30px 16px;
>
> +  margin-bottom: 90px;
>
> +  transition: all ease-in-out 0.2s;
>
> +}
>
>
>
>    - Good job using the FlexBox for project cards. Please use the CSS grid
>    for the project's main container as requested in the project requirements.
>    [image: image]
>    <https://user-images.githubusercontent.com/83803414/187044801-324bd5fb-3e83-4bb5-873e-eaabd0d7e483.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#pullrequestreview-1087711834>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZY3YZEODZEXCA2GJ7KTDQDV3JSEPANCNFSM57ZCULNQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-08-27 23:08 UTC, eyoab01 commented
I will change it, but  I kindly request you to consider  The deadline
approaching. Can you finish for me please?
Thank you,

On Sun, Aug 28, 2022 at 2:11 AM Tesfaye Teklu ***@***.***>
wrote:

> Got it, thanks!
>
> On Sat, Aug 27, 2022 at 10:13 PM Ranjeet Singh ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> STATUS: CHANGES REQUIRED ♻️ Hi @eyoab01 <https://github.com/eyoab01>👋,
>>
>> Good job so far!
>> There are some issues that you still need to work on to go to the next
>> project but you are almost there!
>> To Highlight 🎉
>>
>>    - No linter errors. ✔️
>>    - GitHub flow is followed. ✔️
>>    - Professional README file. ✔️
>>    - PR has a good title and summary. ✔️
>>
>>
>> <https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966>
>> Required Changes ♻️
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>> the approval of this PR. However, I strongly recommend you to take them
>> into account as they can make your code better.*
>>
>> You can also consider:
>> N/A
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>> ------------------------------
>>
>> In index.html
>> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#discussion_r956613911>
>> :
>>
>> > +      <div class="card">
>>
>> +        <div class="card-img">
>>
>> +          <img src="./images/Snapshoot-Portfolio-4.png" alt="Tonic" />
>>
>> +        </div>
>>
>> +
>>
>> +        <div class="details">
>>
>> +          <h2>Multi-Post Stories</h2>
>>
>> +          <ul>
>>
>> +            <li>CANOPY</li>
>>
>> +            <li>Back End Dev</li>
>>
>> +            <li>2015</li>
>>
>> +          </ul>
>>
>> +          <p>
>>
>> +            A daily selection of privately personalized reads; no accounts or
>>
>> +            sign-ups required.
>>
>> +          </p>
>>
>> +          <menu>
>>
>> +            <li>HTML</li>
>>
>> +            <li>CSS</li>
>>
>> +            <li>JavaScript</li>
>>
>> +          </menu>
>>
>> +          <a class="btn-action">See Project</a>
>>
>> +        </div>
>>
>>
>>
>>    - Please reduce the left-right margin from the project card and make
>>    sure it matches Figma
>>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1>
>>    the design.
>>
>> Your design
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/83803414/187044668-ac8733dd-84fb-4738-a884-41145a73ed22.png>
>> Figma design
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/83803414/187044676-0b35081f-f6aa-4c95-8ea7-95d228bb844b.png>
>> ------------------------------
>> ------------------------------
>>
>> In style.css
>> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#discussion_r956614232>
>> :
>>
>> > +#projects {
>>
>> +  display: flex;
>>
>> +  flex-direction: column;
>>
>> +  align-items: center;
>>
>> +  padding: 142px 142px;
>>
>> +}
>>
>> +
>>
>> +.card {
>>
>> +  display: flex;
>>
>> +  flex-direction: column;
>>
>> +  max-width: 330px;
>>
>> +  background: #fff;
>>
>> +  border: 2px solid #dfe1e6;
>>
>> +  border-radius: 16px;
>>
>> +  box-shadow: 0 0 0.5px 0.25px inset #c8c6c6;
>>
>> +  padding: 16px 16px 30px 16px;
>>
>> +  margin-bottom: 90px;
>>
>> +  transition: all ease-in-out 0.2s;
>>
>> +}
>>
>>
>>
>>    - Good job using the FlexBox for project cards. Please use the CSS
>>    grid for the project's main container as requested in the project
>>    requirements.
>>    [image: image]
>>    <https://user-images.githubusercontent.com/83803414/187044801-324bd5fb-3e83-4bb5-873e-eaabd0d7e483.png>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#pullrequestreview-1087711834>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZY3YZEODZEXCA2GJ7KTDQDV3JSEPANCNFSM57ZCULNQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***
>> com>
>>
>

2022-09-22 10:51 UTC, Nemwel-Boniface requested changes
## Hello @eyoab01      :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 10:51 UTC, Nemwel-Boniface commented on style.css
> +}
- [ ] As requested by the [previous reviewer](https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#discussion_r956614232), kindly ensure that you use CSS grid to layout the elements in the main container.

![image](https://user-images.githubusercontent.com/86318284/191724133-e1d37ab5-757c-4189-9d09-d90deb192538.png)

2022-09-23 12:52 UTC, Santiago220991 requested changes
Hi @eyoab01 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-23 12:52 UTC, Santiago220991 commented on style.css
> +}
As requested by the last code reviewer kindly ensure that you use CSS grid to layout the elements in your #projects container. This is part of the requirements of the project. :scroll:

2022-09-23 15:28 UTC, eyoab01 commented
Thanks for the feedback!

On Fri, Sep 23, 2022 at 3:52 PM Santiago Cárdenas ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @eyoab01 <https://github.com/eyoab01> ,
>
> Good job so far!
> There are some issues that you still need to work on to prepare your
> project for the final evaluation but you are almost there!
>
>
> <https://camo.githubusercontent.com/7e9210dcfdfd707fee9896010cd3908fb63e8afc568301ba1c1d5cba19e1499f/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966>
> Suggested changes
>
> *Check the comments under the review.*
>
> You can use as many of my suggestions as you want. If there is anything
> you would like to skip - feel free to do that. However, I strongly
> recommend you to take them into account as they can make your code better._
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> In style.css
> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#discussion_r978601898>
> :
>
> > +#projects {
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  align-items: center;
>
> +  padding: 142px 142px;
>
> +}
>
>
> As requested by the last code reviewer kindly ensure that you use CSS grid
> to layout the elements in your #projects container. This is part of the
> requirements of the project. 📜
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eyoab01/mobile-portfolio-project-final/pull/1#pullrequestreview-1118404554>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZY3YZAAQBTVKSJGSNXWJ63V7WRZDANCNFSM57ZCULNQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-09-23 16:15 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @eyoab01 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️

### As requested by the last code reviewer kindly ensure that you use CSS grid to layout the elements in your #projects container. This is part of the requirements of the project. 📜

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 12:20 UTC, Qoosim approved these changes
#   *Status: Approved* :tada: 

Hi @eyoab01, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Correct GitHub flow. :heavy_check_mark: 
-   Good commit messages. :heavy_check_mark: 

![](https://camo.githubusercontent.com/4f7ec523539917e3ca902dee16c74e3ab543e79be8bf678be6858dce4a8d173e/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a3247506c6a70764c384c756c6d336430582f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 11:00 UTC, merged